config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
hello:
  outputs:
    prod:
      dbname: warehouse
      host: 10.141.14.45
      pass: password
      port: 6432
      schema: analytics
      threads: 8
      type: postgres
      user: transformer
  target: prod
